apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unpoller.fullname" . }}
  labels:
    {{- include "unpoller.labels" . | nindent 4 }}
stringData:
  up.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
